### ISSUE TITLE
CocList -I words does not work on Vim help 

### ISSUE THREAD

**Issue by hydeik** [neoclide/coc-lists#10]
Hello.

I frequently use `CocList -I words` to search buffer. It works quite well, except on Vim help buffer. For example, `:help coc-nvim` and `:CocList -I --input=coc words` returns empty list.

Is this expected behavior?

**Comment by chemzqm** [comment]
Fix on coc.nvim 30d7cb1dba1a82c3a5faac2f224ee0501ddf2533
