### ISSUE TITLE
Tags search is slow

### ISSUE THREAD

**Issue by ravisumit33** [neoclide/coc-lists#100]
I recently switched from fzf to coc for tags searching in the workspace. But I found tags searching in coc slow as compared to fzf. 

In COC:
`:CocList tags`

![coc_trimmed](https://user-images.githubusercontent.com/19284116/99502941-c404f780-29a3-11eb-9058-3ac802ae1fc1.gif)

In FZF:
`:Tags`
![fzf_trimmed](https://user-images.githubusercontent.com/19284116/99503585-63c28580-29a4-11eb-9372-66c52f5b56fa.gif)

As can be seen, coc is very slow compared to fzf.

**Comment by chemzqm** [comment]
It's your language server that slow for symbols search, send your feature request to the developer of your server.

**Comment by ravisumit33** [comment]
I was using `:CocList tags` itself. First gif is corresponding to `:CocList tags`

**Comment by ravisumit33** [comment]
@chemzqm I think this should be improved.

**Comment by chemzqm** [comment]
Looks lie your tag file is very big

**Comment by ravisumit33** [comment]
Yes, but with the same tags file fzf is very fast.
