### ISSUE TITLE
macOS cmd-v not work

### ISSUE THREAD

**Issue by ZhiruiLi** [neoclide/coc-lists#101]
When using vim under macOS, it is normal to use cmd-v to paste text. It works for vim buffer, vim command, but not work for CocList. Any idea for solving this?

Environment info:

```
macOS 10.15.7
```

```
## versions

vim version: NVIM v0.4.4
node version: v15.2.1
coc.nvim version: 0.0.79-1cf07be052
term: iTerm.app
platform: darwin
```

**Comment by chemzqm** [comment]
Because `getchar` can't use with paste,  read `:h coc-list-mappings-custom*`

**Comment by ZhiruiLi** [comment]
> h coc-list-mappings-custom

But `coc-list-mappings-custom` can't accept cmd key mapping which starts with `<D-`:

> Note: you should only use mappings that start with <C- or <A- for insert mappings.

**Comment by chemzqm** [comment]
It's terminal vim that can't make use of `<D-`, there's a prompt action to paste text from clipboard.

**Comment by ZhiruiLi** [comment]
> It's terminal vim that can't make use of `<D-`, there's a prompt action to paste text from clipboard.

Even if I use VimR, I still can't map `<D-`.
I don't understand, is it impossible to paste by cmd-v?

**Comment by chemzqm** [comment]
You can't, I have said `getchar` can't work with paste mode, it's vim issue.

**Comment by ZhiruiLi** [comment]
Emm... I just wonder why other plugins like FZF can support this?

**Comment by chemzqm** [comment]
FZF runs in terminal, it not using `getchar`

**Comment by ZhiruiLi** [comment]
Thanks

**Comment by chemzqm** [comment]
It's possible to paste text by `<cmd-v>` in terminal, you can remap `<cmd-v>` to send `<ctrl-v>` to vim in your terminal profile, and remap `<C-v>` to `prompt:paste` in `list.normalMappings` of settings file.

**Comment by ZhiruiLi** [comment]
Oh, I should give it a try

**Comment by chemzqm** [comment]
It's bad idea since you can't paste in your teminal shell by using `<cmd-v>` any more.

**Comment by ZhiruiLi** [comment]
That's right, I've tried it and found it not suit to me
