### ISSUE TITLE
Searches in `:CocList mru` break the MRU order

### ISSUE THREAD

**Issue by arbitrary-dev** [neoclide/coc-lists#103]
## Issue

When browsing `:CocList mru`, I'd like to use search to quickly find recently used buffers containing the phrase. But as soon as search kicks in, the order of buffers seems to be switched to an ordinary alfanumeric one.

**Comment by chemzqm** [comment]
Use `--no-sort` option.

**Comment by arbitrary-dev** [comment]
`:CocList --no-sort mru` to be exact, not after "mru".

Thanks!
