### ISSUE TITLE
Sessions provider fuzzy sorting is broken

### ISSUE THREAD

**Issue by BonaBeavis** [neoclide/coc-lists#105]
## System

- Coc: c9333a71
- Nvim: v0.5.0-884-gd95684275
Only coc plugin is enabled.

## Reproduce

1. `:CocList sessions`
2. Type: auto
3. Result:

![image](https://user-images.githubusercontent.com/3330855/100601814-5cd03700-3303-11eb-9943-444cfca40646.png)

## Expected

Session autosticker should be first. Other sources match and sort correctly.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
