### ISSUE TITLE
Open file in new tab or split

### ISSUE THREAD

**Issue by rjurado01** [neoclide/coc-lists#107]
It is possible to open file from results in new tab or split?

For example: `Use <c-t> or <c-v>, <c-x> to open the selected entry in a new tab or in a new split.`

Thanks for your job.

**Comment by chemzqm** [comment]
`:h coc-list-mappings`

**Comment by rjurado01** [comment]
@chemzqm Thanks!!

It would be nice to add it to REAME

**Comment by chemzqm** [comment]
No, that's too long

**Comment by rjurado01** [comment]
> No, that's too long

I mean the command

**Comment by chemzqm** [comment]
> Checkout :h coc-list for usage.

Already exists.
