### ISSUE TITLE
Location list is rendered red and very blurry

### ISSUE THREAD

**Issue by wirtsi** [neoclide/coc-lists#108]
Hey ...

it's just a small thing but it bugs me because I can't properly read the file names. When using CocList to render the location list, it is always rendered in red with a super blurry font (the right font, but somehow totally blurred). This also happens when opening eg. a method's reference with gr

NVIM v0.5.0-dev+5fcc247 
coc-lists 1.3.16
coc.nvim 0.0.80

![image](https://user-images.githubusercontent.com/276751/103778088-0ce73d00-5032-11eb-8af9-149994812554.png)

No idea where this styling comes from. When I switch to another color theme and back to the initial one (with the list still open) it looks like this (which is how it should be I assume)

![image](https://user-images.githubusercontent.com/276751/103778185-2daf9280-5032-11eb-9ed4-741eaf9a3739.png)

Any idea where this might come from? Every other list looks ok ...

**Comment by chemzqm** [comment]
Try minimal vimrc.

**Comment by wirtsi** [comment]
It was the same with a minimal vimrc ... but I found out what it was. Turns out that my monitor doesn't properly support HDR. When I disabled it, the blurriness disappeared. So sorry for the commotion ... still it would be nice to know how to properly style the text (so it's not red) :-)
