### ISSUE TITLE
[feature request] Custom action

### ISSUE THREAD

**Issue by MaiLunJiye** [neoclide/coc-lists#110]
通常情况下大部分action已经够用了，但是我希望可以提供自定义添加特定源action的api，
比如 files 源 可以添加  xdg-open 和 execute 的专用 action。
这样当搜索出某些文件比如 png，jpeg 时候，可以直接打开，而不是以二进制形式在nvim中打开。

**Comment by chemzqm** [comment]
没有必要，CocList 支持映射自定义 vim 函数，你自己实现就行了
