### ISSUE TITLE
After deleting/wiping the current buffer there is an enormous padding under status line

### ISSUE THREAD

**Issue by osenvosem** [neoclide/coc-lists#118]
After deleting or wiping the current buffer from the list status line moves far up and there is a huge empty space under it.

![Screenshot 2021-05-23 at 21 59 43](https://user-images.githubusercontent.com/6762673/119273198-726b4d00-bc12-11eb-904a-0a155e641f71.png)

**Comment by chemzqm** [comment]
It's expected since list window takes fixed height, please avoid close original window.

**Comment by osenvosem** [comment]
@chemzqm this is very strange behaviour from a user point of view. Why isn't it switch to another opened buffer when I delete the current or open an empty buffer if it was the last one (the default vim behaviour)?

**Comment by chemzqm** [comment]
You need to understand window & buffer first.
