### ISSUE TITLE
Syntax highlighting doesn't work in list preview window with treesitter

### ISSUE THREAD

**Issue by ravisumit33** [neoclide/coc-lists#120]
When opening list preview, filetype is not set due to which syntax highlighting (I am using nvim-treesitter) doesn't work. Other syntax plugins like [vim-polyglot](https://github.com/sheerun/vim-polyglot) works. If I manually set filetype of list preview window syntax highlighting with treesitter works very well.

I think there is a need to set filetype when opening list preview window.

**Comment by chemzqm** [comment]
it's intended to highlight range of preview window (instead of set filetype) for performance reason, you can hack this function https://github.com/neoclide/coc.nvim/blob/master/autoload/coc/list.vim#L220
