### ISSUE TITLE
no tag files found(coc-list)

### ISSUE THREAD

**Issue by zombo** [neoclide/coc-lists#125]
Windows 10
Vim 8.2.2366

run "CocCommand tags.generate", echo "tagfile generated"

in my coc-setting, 
`
    "list.source.tags.command": "gtags --skip-symlink=a --gtagsconf d:\\software\\gtags\\share\\gtags\\gtags.conf --gtagslabel native-pygments",

`
and I have generated tags using "ctags -R .", too.
so, in my src dir, there are "GTAGS" and "tags"

however, I run coc-definition, echo "definition not found"
and
run "CocList tags", echo "no tag files found, use ":CocCommand tags.generate" to generate tagfile."

I check the source. it need call tagfiles(), but in my gvim, it echo "[]", when call tagfiles(). So, should I config the tagfiles to make coc-list works.

and could coc-list support gtags?
`
  async loadItems(_context) {
    let {nvim} = this;
    let cwd = await nvim.call("getcwd");
    let tagfiles = await nvim.call("tagfiles");
    if (!tagfiles || tagfiles.length == 0) {
      throw new Error('no tag files found, use ":CocCommand tags.generate" to generate tagfile.');
    }
    let task = new FileTask();
    task.start(tagfiles, cwd);
    return task;
  }

`

**Comment by chemzqm** [comment]
`:h 'tags'`
