### ISSUE TITLE
Inconsistency of searching methods.

### ISSUE THREAD

**Issue by sloppydevil** [neoclide/coc-lists#131]
when using :CocList grep, regular expression didn't work. maybe due to that I don'w know the proper re version?

when using \<space\>s, it goes to symbols, fuzzy methods or regex didn't work, only strict literal.

maybe how the three ways (strict, fuzzy, regex) work is written somewhere?

thx so much!

**Comment by chemzqm** [comment]
See `interactive` sectin of  `:h coc-list-options`

**Comment by sloppydevil** [comment]
configured in :CocConfig as follows, when input :CocList symbols. No regex was supported. 😩	
"list.source.symbols.defaultOptions": [
		"--interactive",
		"--regex",
		"--number-select",
		"--ignore-case"
	],
