### ISSUE TITLE
search a specific folder doesn't work

### ISSUE THREAD

**Issue by jackielii** [neoclide/coc-lists#133]
per https://github.com/neoclide/coc-lists/issues/58, I should be able to do:

```
execute 'CocList grep hello' . expand('%:p:h')
```

To grep for word `hello` from the folder of current file. However the options produced by grep is:

```
rg --fixed-strings --color always --max-columns 300 --vimgrep hello /path/to/current/folder -- ./
```

The problem is https://github.com/neoclide/coc-lists/blob/master/src/grep.ts#L168 always include cwd `./`

I propose adding a new option to ignore current folder

**Comment by chemzqm** [comment]
Added check for `--`

**Comment by jackielii** [comment]
Thanks so much for the fast response. Added pr #134
