### ISSUE TITLE
Custom menu

### ISSUE THREAD

**Issue by adelarsq** [neoclide/coc-lists#14]
This is not a issue. It's possible with this plugin to make something like [quickmenu](https://github.com/skywind3000/quickmenu.vim)? The idea is to be possible populate commands and descriptions in vimrc and by others plugins :slightly_smiling_face:

**Comment by chemzqm** [comment]
>  populate commands and descriptions in vimrc and by others plugins 

Don't understand, please explain.

**Comment by adelarsq** [comment]
@chemzqm  Actually with `CocList vimcommands` is possible to get a list with all commands from Vim. My idea is to make a custom list that can be created by demand, on the vim configuration files and/or by others plugins. So with this list we can make fuzzy search in the command list (something like [Denite menu](https://github.com/Shougo/denite.nvim/blob/b67a9983f29463a0d9e7e0b639d7a429be88a979/doc/denite.txt#L168-L188))

**Comment by chemzqm** [comment]
Function `coc#add_command()` is added, checkout https://github.com/neoclide/coc.nvim/commit/4fee42c30c03d51b8cb213b9651ea996b4d842a9
