### ISSUE TITLE
Support for helptags, command and search history

### ISSUE THREAD

**Issue by erlais** [neoclide/coc-lists#2]
This is the first time I'm giving feedback to coc.nvim in general, so I want to thank you @chemzqm for the amazing work on this plugin. I love it and the speed of it improving is staggering!

I am currently replacing fzf plugin with CocList. Are there any plans to add lists for helptags, command history and search history? I know there are other, vim native, commands for achieving this, but I'm used to this fzf type workflow. I'm willing to contribute if you think these should be added.

[Helptags search in fzf.vim](https://github.com/junegunn/fzf.vim/blob/master/autoload/fzf/vim.vim#L980)

**Comment by chemzqm** [comment]
Sure, will add them, contribution welcome.
