### ISSUE TITLE
[Bug report] Can not close list using <Esc>

### ISSUE THREAD

**Issue by voldikss** [neoclide/coc-lists#21]
- 版本: `NVIM v0.4.0-dev`

- 最小化vimrc: 
```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile', 'frozen':1}
call plug#end()
```

- 复现步骤:
    - `:CocList --normal<CR>`
    - `:` (按 `:`进入底部命令行窗口)
    - `<Esc>` (按`<Esc>`，此时光标应该位于 list 窗口)
    - `<Esc>` (无法关闭 list 窗口)

**Comment by chemzqm** [comment]
暂时就是这样工作的，因为 `:` 取消了 prompt， coc 接收不到输入事件。

**Comment by voldikss** [comment]
嗯嗯，我知道了。所以这个暂时不归为 bug，或者要 fix 的话需要改动太多吗？

**Comment by chemzqm** [comment]
修复了
