### ISSUE TITLE
can't open mru files when upgrade coc-nvim

### ISSUE THREAD

**Issue by YUFENGWANG** [neoclide/coc-lists#26]
I have just upgrade my coc-nvim to 0.0.69. and coc-list `mru` feature seems broken. when I select a mru file and hit enter, nothing happens. But before upgrading, I can open `mru` files either hit enter or with my custom key binding after selected

**Comment by chemzqm** [comment]
Please provide your `:CocInfo`

**Comment by YUFENGWANG** [comment]
```bash
## versions

vim version: NVIM v0.3.4
node version: v10.15.0
coc.nvim version: 0.0.69-ec73f3f3f1
term: iTerm.app
platform: darwin

## Messages

## Output channel: prettier


## Output channel: watchman


## Output channel: snippets

[Info  - 17:29:36] watchman watching project: /Users/richard/.config/coc/ultisnips
[Info  - 17:29:36] subscribing "**/*.snippets" in /Users/richard/.config/coc/ultisnips


```

**Comment by YUFENGWANG** [comment]
@chemzqm

**Comment by chemzqm** [comment]
Can't reproduce, please provide minimal vimrc.

**Comment by chemzqm** [comment]
Don't use `{'tag': '*', 'do': { -> coc#util#install()}}`
