### ISSUE TITLE
Cyrillic popup menu - not shown

### ISSUE THREAD

**Issue by D1mon** [neoclide/coc-lists#27]
autocomplete works, no popup menu is displayed in current buffer:
https://www.dropbox.com/s/4kipjaef6fzuzil/2019-06-11%2014-33-00.mkv?dl=0

**Comment by chemzqm** [comment]
Can't reproduce.

**Comment by D1mon** [comment]
do you work? maybe there is a problem in the settings?

**Comment by chemzqm** [comment]
I have reproduced.

**Comment by chemzqm** [comment]
Fixed on master of coc.nvim.

**Comment by D1mon** [comment]
Thank you!
