### ISSUE TITLE
List source `file` is not available on Windows

### ISSUE THREAD

**Issue by mzr1996** [neoclide/coc-lists#30]
CocInfo:
* vim:
```
vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled May 18 2018 18:26:56)
node version: v12.4.0
coc.nvim version: 0.0.72-457d77287e
term: undefined
platform: win32
```
* neovim:
```
## versions

vim version: NVIM v0.4.0-819-g66d127957
node version: v12.4.0
coc.nvim version: 0.0.72-457d77287e
term: undefined
platform: win32
```

Terminal:
* powershell
* cmd
* Gui environment such as gvim and nvim-qt

System:
Windows 10 Home Basic 1903

Problem:
The list source `file` is empty like this picture:
![图片](https://user-images.githubusercontent.com/26739999/60501186-306b5200-9cee-11e9-83c9-02aa4c9ce48d.png)

While other list sources, like `mru` and `buffers`, are all available.
![图片](https://user-images.githubusercontent.com/26739999/60501486-b38ca800-9cee-11e9-8d6b-32453e5113ae.png)

And the list source `file` is available in my Linux system with the same `.vimrc` file.

**Comment by chemzqm** [comment]
It use `dir` comand on windows when rg and ag not found, which could be quite slow.

**Comment by mzr1996** [comment]
> 
> 
> It use `dir` command on windows when rg and ag not found, which could be quite slow.
> Or your cwd is just empty.

Well, you reminded me that I ever downloaded `ag` and put it into the environment path.
I just removed it and now the list sources `file` works correctly...

Maybe there is something wrong when it works with `ag`?
Here is my `ag --version`
```
ag version 2.2.0

Features:
  +jit +lzma +zlib
```

**Comment by chemzqm** [comment]
It use `ag -f -g . --nocolor` by default, you can customized it.
