### ISSUE TITLE
Floating coc-list

### ISSUE THREAD

**Issue by parker789** [neoclide/coc-lists#33]
Is this possible?

**Comment by chemzqm** [comment]
It's possible, but would make CocList much harder to maintain, so there would be floating list that only support float.

**Comment by parker789** [comment]
Hmm, I need to take a look at the internals of vim moreso. I'm assuming I could write some custom functions to handle this and maintain it on my own?

**Comment by chemzqm** [comment]
Sure, you're free to fork coc.nvim.

**Comment by parker789** [comment]
tysir!
