### ISSUE TITLE
Help with "find current word in all workspace files"

### ISSUE THREAD

**Issue by esn89** [neoclide/coc-lists#35]
Hi, 

I am trying to move away from fzf.  One of the functions I like to have is using grep/rg, to be able to find the word that is currently under my cursor and then in the list, show all the places in the workspace where such a word exists.

Here is what it looks like in fzf:

https://i.imgur.com/sfw12uI.png

My cursor is under the word "raise".  I use my mapping of <Leader>cf and I'm able to see in fzf all the **files** and **lines numbers** where such word exists.

I would like to achieve the same thing using coc-lists.  So far, without success.  I tried to make a command like:  
```
nnoremap <silent> <Leader>cf  :CocList grep --input='.expand('<cword>').'<CR>

But that didn't work.  Any help would be appreciated.

**Comment by chemzqm** [comment]
Read https://github.com/neoclide/coc-lists/blob/master/Readme.md#f.a.q

**Comment by esn89** [comment]
Thanks a million.

**Comment by nomasprime** [comment]
Hi @chemzqm. It seems like the last line will do, similar to the current word in buffer example. What are the first few lines for?

```viml
command! -nargs=+ -complete=custom,s:GrepArgs Rg exe 'CocList grep '.<q-args>

function! s:GrepArgs(...)
  let list = ['-S', '-smartcase', '-i', '-ignorecase', '-w', '-word',
        \ '-e', '-regex', '-u', '-skip-vcs-ignores', '-t', '-extension']
  return join(list, "\n")
endfunction
```

It's really the first line I haven't understood.

**Comment by nomasprime** [comment]
Ah, think I get it. They're simply separate things: lines above define a separate function with autocomplete and the last line is similar to the word in current buffer example.

Great, I learnt some VimL today 😁
