### ISSUE TITLE
List Tags in Current Buffer

### ISSUE THREAD

**Issue by frithrah** [neoclide/coc-lists#4]
Is the fzf BTags command (listing tags of the current buffer) possible in coc-lists?

[BTags in fzf.vim](https://github.com/junegunn/fzf.vim/blob/master/autoload/fzf/vim.vim#L725)

**Comment by chemzqm** [comment]
There is `:CocList outline`, but it's using symbols from language server, I'll improve it support tags when no document symbols provider found.

**Comment by frithrah** [comment]
Sounds like a great plan. Love your work. Thank you.

**Comment by chemzqm** [comment]
It's supported on master of coc.nvim https://github.com/neoclide/coc.nvim/commit/f01279db77f9b9e0ada8571e43446a43540fa926

**Comment by frithrah** [comment]
This is excellent. A great addition to CoC to support archaic languages where no LSP is forthcoming.

One thing, if the first ctags command (outline.ts:84) finds nothing then the content var will be undefined so the trim call will fail (outline.ts:88). I added a check on content first and then the second fall-back ctags command ran fine.

**Comment by chemzqm** [comment]
Ok, I've fixed that.
