### ISSUE TITLE
[question] Pass custom arguments to grep

### ISSUE THREAD

**Issue by terkelg** [neoclide/coc-lists#46]
I like the default behavior of excluding hidden files when doing a `CocList files` or `CocList grep` command. However, it happens that I also want to search hidden files sometimes. How can create a mapping that allows me to pass `--hidden` to ripgrep?

I know it's possible with the configuration: `list.source.files.args: ['--hidden', '--files']` but I'm not interested in changing the default behavior.

According to the documentation, there's an argument option `:CocList [LIST OPTIONS] files [ARGUMENTS]` but these are for `coc-list` and not passed down to ripgrep.

Thank you 🙏

**Comment by chemzqm** [comment]
The arguments are passed to ripgrep

**Comment by terkelg** [comment]
Maybe I'm formatting it wrong. I've tried `CocList grep --hidden --files`, `CocList grep -hidden -files`, `CocList grep ['hidden', 'files']` and `CocList grep ['--hidden', '--files']`

**Comment by chemzqm** [comment]
Press `?` on normal mode

**Comment by terkelg** [comment]
I already tried that but the documentation only lists `-F` and `-W`. 
I cannot find any documentation for arguments that allow hidden files – and when I try to pass in the arguments from the `ripgrep` documentation (like `-hidden` and `-files`) it does not work. 

Doing `?` for `CocList grep` provides more arguments, but still none that allow hidden files. The closets are `-u` to ignore version control files.

**Comment by fannheyward** [comment]
You can't use `grep` for your action, cause grep is defined for text finding in coc-lists. I just make a PR to add extra args in `files`, you can use something like this: `:CocList files [-F] --hidden`, where `-F` is files options.

**Comment by chemzqm** [comment]
Improved files source for additional command arguments, grep source have support for that, like:
```
CocList grep --hidden abc
```
