### ISSUE TITLE
Unable to ignore `**/.git/*` in `CocList files`

### ISSUE THREAD

**Issue by chhschou** [neoclide/coc-lists#47]
I set the `"list.source.files.excludePatterns": ["**/.git/*"],`
The list still contains files from the .git directory. Am I doing something wrong?

![Screenshot from 2019-08-12 13-29-09](https://user-images.githubusercontent.com/429067/62842365-ce970280-bd05-11e9-811c-625e117a0ba4.png)

**Comment by chemzqm** [comment]
Use `  "list.source.files.excludePatterns": ["**/.git/**"],`

**Comment by nomasprime** [comment]
This doesn't work for me. Working for others?

**Comment by nomasprime** [comment]
Tried adding `"--glob '!.git'"` to `"list.source.files.args"`, doesn't work either.

**Comment by chemzqm** [comment]
It depends on what program you're using for files source.

**Comment by nomasprime** [comment]
Makes sense, thanks for clarifying.
