### ISSUE TITLE
coc and vim-obsession

### ISSUE THREAD

**Issue by mg979** [neoclide/coc-lists#49]
## Describe the bug

When using coc and vim-obsession, the obsession informations in the session file are lost when quitting, leading to a normal session file that isn't handeld by obsession anymore.

## Reproduce the bug

- save a session with `Obsession filename`
- quit
- start nvim and the session
- quit again
- start nvim and the session again, `g:this_obsession` doesn't exist anymore and session isn't tracked

**Comment by chemzqm** [comment]
It's problem of vim-obsession, add `"session.saveOnVimLeave": false` to coc-settings.json to avoid session save on vim leave.

**Comment by mg979** [comment]
Isn't it a problem of coc overwiting the session file without asking, and without the user knowing anything? Is session update needed for coc, or is it just an 'hidden bonus'?

 I tried to put that in ~/.vim/coc-settings.json and ~/.config/nvim/coc-settings.json, but nothing changes (it still clears the variable and overwrites the session file), not sure if the settings file is in the right location though.

**Comment by mg979** [comment]
And by the way, if I run CocConfig it will ***CREATE*** directories at the current location (something like ./normal/coc-settings.json), instead of opening the default file, forcing me to delete that useless dir (normal??).

Another issue I found is that when using the integrated fuzzy finder, the cursor shape is changed but not restored...

And sorry for the tones, but these are infuriating things for me, I'm reporting just so that you know it, I'm not using the plugin right now, certainly I won't in the future if it keeps being so invasive.

**Comment by chemzqm** [comment]
It should be problem of your confoguration and bug of vim, try minimal vimrc, you're free to not use it

**Comment by mg979** [comment]
Sorry for sounding polemic. I can't reproduce these problems with a minimal vimrc, but the thing about coc creating ./normal/ directories is clearly a bug in coc, not in vim, and the fact it's not reproducible with a minimal vimrc means nothing in this case, unless you're suggesting to use coc with a minimal vimrc...

**Comment by chemzqm** [comment]
Don't what happened

**Comment by mg979** [comment]
Ok I found out:

https://github.com/neoclide/coc.nvim/blob/e9ef666cb51ed23c2ad6ae3349a40f8d587e635c/autoload/coc/util.vim#L349

You are using an environmental variable $VIMCONFIG that I actually use to define the type of vimrc running (normal, minimal). How can you assume a non-standard environmental variable to do what you think it would do, and even autocreate directories based on this assumption? Don't tell me it's a standard because the vim manual does no mention of this variable. There are only 2 standard vim directories (.vim and vimfiles in Windows), I don't know in nvim. You should only search there or force the user to point to a different location, if not found there. You can't have coc make guesses and create directories at random locations.... That's what it's doing.

**Comment by chemzqm** [comment]
It is by design.

**Comment by mg979** [comment]
I fixed it if you are interested in a PR. It won't autocreate directories, though (by design).
