### ISSUE TITLE
:CocList grep does not work

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc-lists#5]
`:CocList`
selecting grep
typing into the prompt works as expected.

`:CocList grep`
typing into the prompt nothing happens. No results are shown

**Comment by chemzqm** [comment]
You need to add `-I` as list option for interactive grep.

**Comment by Avi-D-coder** [comment]
Same issue with words, but `-I` does not solve it

**Comment by chemzqm** [comment]
You can't use `-I` at the end, use it before list source name.

**Comment by Avi-D-coder** [comment]
I had forgotten about that.  A warning when using it wrong might be useful
