### ISSUE TITLE
Searching using spaces returns no results

### ISSUE THREAD

**Issue by arbitrary-dev** [neoclide/coc-lists#50]
:CocConfig
```
{
  "list.source.grep.command": "ag",
  "list.source.grep.args": ["-i"]
}
```

Minimal example:
```
$ cat <<EOF > file.txt
heredoc> asdasd
heredoc> cv er
heredoc> EOF

$ ag "v e"
file.txt
2:cv er
```

Both return no results:
```
:CocList grep e v
:CocList grep "e v"
```

**Comment by chemzqm** [comment]
You have to use `\` to escape space in vim command

**Comment by arbitrary-dev** [comment]
What about `INTERACTIVE` mode? `\` doesn't works there.

**Comment by chemzqm** [comment]
You should use input option to pass input for interactive list, please read the doc.

**Comment by arbitrary-dev** [comment]
I don't get it…

```
<space>g

-- INSERT --  grep (1/0)
INTERACTIVE > --input "v e"

<nothing>
```
 
What?

Could you please provide a link to the docs you're talking about?  
[The only one](https://github.com/neoclide/coc-lists) I've found is talking about adding keymapping with `--input "text"` embedded, but that's not interactive mode.

**Comment by chemzqm** [comment]
`:h coc-lists`

**Comment by arbitrary-dev** [comment]
I think there's a misunderstanding…

My workflow is this:
```
:CocList grep
INTERACTIVE > e v
```

Space is not working above, neither escaping it with `\`.

As I understood from the docs, the `--input` requires me to provide `ag`'s output manually for later interactive session.

**Comment by nomasprime** [comment]
Searched docs but can't find anything. Straightforward answer would be appreciated.
