### ISSUE TITLE
Options to hide parts of buffer source

### ISSUE THREAD

**Issue by shtanton** [neoclide/coc-lists#51]
Another feature request:
Can I send a PR to add some options to hide parts of the buffer list.
I'm probably not the only person who uses only the file name most of the time, so it'd be nice to have only that shown, but I could easily add 3 flags to hide each of the 3 columns.

**Comment by chemzqm** [comment]
Why? You can use mru source or files source instead.

**Comment by chemzqm** [comment]
The files have mru support builtin, so it's better if you just want to open files.
