### ISSUE TITLE
Unable to ignore node_modules in project.

### ISSUE THREAD

**Issue by elrrrrrrr** [neoclide/coc-lists#52]
![image](https://user-images.githubusercontent.com/5574625/63215473-673fdf00-c159-11e9-8d19-ed4b6948e305.png)

![image](https://user-images.githubusercontent.com/5574625/63215568-14ffbd80-c15b-11e9-8439-3994053d4f13.png)

As the pic shows.
The git configuration works fine, but node_modules does not take effect.
since the node_modules contain the hidden files

**Comment by elrrrrrrr** [comment]
```json
{
  "list.source.files.excludePatterns": ["**/node_modules/**", "**/node_modules/**/.*", "**/node_modules/**/.*/**"],
}
```
This configuration can be temporarily compatible with this problem.

**Comment by chemzqm** [comment]
Use rg or ag with  gitignore file
