### ISSUE TITLE
Unexpected behavior when searching maps

### ISSUE THREAD

**Issue by yzlnew** [neoclide/coc-lists#59]
For example, I have mapped `gd` to `coc-definiton`.
I can search `gd` to get this keymap.

![Snipaste_2019-10-16_15-39-48](https://user-images.githubusercontent.com/4904877/66898229-5d3c3e80-f02b-11e9-88e0-94838ae55a60.png)

When I use `definition` to search, it doesn't come up in results.

![Snipaste_2019-10-16_15-40-01](https://user-images.githubusercontent.com/4904877/66898257-704f0e80-f02b-11e9-86f7-9530cdd8f1b4.png)

**Comment by fannheyward** [comment]
Yes, this is by designed, only mapping key is used for fuzzy filter https://github.com/neoclide/coc-lists/blob/master/src/maps.ts#L47 .
