### ISSUE TITLE
How to change currently selected item's highlight color?

### ISSUE THREAD

**Issue by kencoder97** [neoclide/coc-lists#60]
I want to change the color of current selected item in CocList. How can I do that?
Thank you!
<img width="844" alt="Screen Shot 2019-10-17 at 00 28 41" src="https://user-images.githubusercontent.com/26746668/66943453-65b96700-f075-11e9-9fd6-a8ffb0bde335.png">

**Comment by chemzqm** [comment]
change CursorLine highlight group
