### ISSUE TITLE
Feature request: Use floating window

### ISSUE THREAD

**Issue by giovannigiordano** [neoclide/coc-lists#61]
I've seen vim-clap which uses floating windows for lists.
There is any chance to have this implemented in coc-lists?
Thanks.

**Comment by terkelg** [comment]
I think this could be a nice UI improvement as well. Here's a preview of [vim-clap](https://raw.githubusercontent.com/liuchengxu/vim-clap) and the floating window:
![vim-clap-1024-98](https://user-images.githubusercontent.com/8850248/65813749-d6562c00-e20b-11e9-8161-c42801b1056c.gif)

**Comment by chemzqm** [comment]
Lists are implemented independently of UI, there might be a floating list extension in the future.

**Comment by alex-popov-tech** [comment]
any updates on that? still relevant :)

**Comment by JSamir** [comment]
Would it be a good idea to implement whatever is needed in the floating window as a provider for vim-clap? I have no idea if that is a good idea, just throwing that in here because it seems that vim-clap is nicely extensible.
https://github.com/liuchengxu/vim-clap#how-to-define-your-own-provider

**Comment by chemzqm** [comment]
@JSamir vim-clap or other fuzzy finder can make use API of coc.nvim.

**Comment by tmpm697** [comment]
I prefer current behavior of coc-list but it would be nice if it supports floating window.

**Comment by orlandoxu** [comment]
hope support floating window.

**Comment by orlandoxu** [comment]
Hope support floating window.

**Comment by chemzqm** [comment]
Nope
