### ISSUE TITLE
coc-grep sometimes doesn't work properly 

### ISSUE THREAD

**Issue by hovnatan** [neoclide/coc-lists#64]
In one of my git repos when I try a certain word with coc-grep not all of the instances are found. But if in a different folder I clone the same repo from the remote again the same word is found without any problems. How can I debug this issue? Is there cache that coc-nvim keeps that I can delete? Thanks.

**Comment by chemzqm** [comment]
It uses rg or ag which respect gitignore and .ignore by default.
