### ISSUE TITLE
rg regular expression

### ISSUE THREAD

**Issue by flipxfx** [neoclide/coc-lists#7]
It seems like -e and -regex don't work for rg?

I can only get regex matching by using `:ColList grep -e one|two`. It seems like when using regex, ripgrep want the pattern after like:

`*rg* [_OPTIONS_] *-e* _PATTERN_... [_PATH_...]`

It would be nice if in `-e` was specified in `grep.args` that it would place the search text in the correct place to default to always using regex match.

**Comment by chemzqm** [comment]
`|` need be escped in vim's command, so you should be able to use `:ColList grep -e one\|two`, but it's still broken.

**Comment by flipxfx** [comment]
I'm not sure how to use this to fix my issue?

I want to be able to run `:CocList grep search\ term` and have rg recognize it as regex.

**Comment by chemzqm** [comment]
list.source.grep.useLiteral : false
