### ISSUE TITLE
--auto-preview does not update in vim

### ISSUE THREAD

**Issue by magnus-gross** [neoclide/coc-lists#72]
I have the following keybinding:

`nnoremap <silent> <LocalLeader>P :<C-u>CocList -A files<CR>`

Now if I open this list with autopreview enabled, I successfully get the intended preview of the first file, but if I go to the second result, the autopreview does not change and still shows the same file.
This bug does only exist in vim, not in neovim.

Here is an example screenshot where the preview failed to update (vim on the left, nvim on the right):

![Screenshot_20200202_203313](https://user-images.githubusercontent.com/21310755/73613981-467e1f80-45fb-11ea-94b4-147b0241dd0a.png)

If I type in the line and search for a file, the preview updates again to the first search result.

Config used: https://github.com/magnus-gross/dotfiles/blob/master/vim/.vimrc

**Comment by chemzqm** [comment]
Try update your vim and coc.nvim to latest version.
