### ISSUE TITLE
Is CocList mru supposed to remember file open history between sessions?

### ISSUE THREAD

**Issue by Praful** [neoclide/coc-lists#74]
Hello

Thank you for writing this extension.

I switch from FZFMru to using `CocList mru`. My expectation is that I would see, regardless of session, a list of most recently opened files up to a maximum (default 1000, I think).

However, I see only files opened in current session. If I exit Vim (gvim on Windows), The mru list is empty.

I tried `CocList -A mru` but that didn't show all files.

Please can you explain what I need to do for CocList to remember all files opened not just those in this session.

Thanks

**Comment by chemzqm** [comment]
You have -A on wrong position, move it to the end.
