### ISSUE TITLE
[Feature Request] CocAction('getTags')

### ISSUE THREAD

**Issue by antoinemadec** [neoclide/coc-lists#75]
I would like to implement ```CocList tags``` in [coc-fzf](https://github.com/antoinemadec/coc-fzf/issues/2).
Would it be possible to add a ```CocAction('getTags')``` returning a dict with: name, file, linenb, column?

Thanks in advance!
Antoine

**Comment by chemzqm** [comment]
LSP doesn't have tags, the document symbols API requires `input` to query results, checkout `:h coc-action-getWorkspaceSymbols`.
I think you should just use tags source of fzf.

**Comment by antoinemadec** [comment]
Got it, WorkspaceSymbols is already integrated in coc-fzf.
I will stick with the fzf ```:Tags``` command. Thanks again for the quick response :smiley:
