### ISSUE TITLE
不能识别不以.vim为后缀名的session文件

### ISSUE THREAD

**Issue by yan42685** [neoclide/coc-lists#77]
使用nvim时，Startify把session文件保存在~/.local/share/nvim/session
于是我在CocConfig里设置了"session.directory": "~/.local/share/nvim/session"
然而CocList里的session部分只能找到默认的default.vim 而不会识别不以.vim结尾的session文件 （startify保存session信息的文件没有后缀名
![111](https://user-images.githubusercontent.com/41834091/77807740-b53f9c80-70c3-11ea-843a-22e9b3bb17c5.png)
![2222222222](https://user-images.githubusercontent.com/41834091/77807761-c5f01280-70c3-11ea-9053-6c4ee12c87b6.png)

**Comment by yan42685** [comment]
在命名session的时候自己加上.vim后缀就能被识别了，
就是在startify页面看起来不太美观...

**Comment by chemzqm** [comment]
不解决，只支持 .vim 文件
