### ISSUE TITLE
Current line highlighting for CocLists

### ISSUE THREAD

**Issue by arbitrary-dev** [neoclide/coc-lists#78]
Related to issue #70.

Currently selected items in CocLists use `CursorLine` highlighting group, but it causes problems (current line isn't highlighted in CocLists) for Vim users which use `cursorline` only for line numbers:
```
set cursorline
hi CursorLineNr ctermbg=red
hi CursorLine ctermbg=none
```

Proposal is to have a separate highlighting group for CocLists selection or `set number` for CocLists buffer.

**Comment by agtonybarletta** [comment]
Nervermind, by typing `:CocList maps` it shows all the key bindings, two of which are `<c-j>`  and  `<c-k>` that do what you expect.

**Comment by chemzqm** [comment]
We have to use cursorline, you can use command like:
```
  autocmd FileType list set winhighlight=CursorLine:CocUnderline
```
which works on neovim only

**Comment by arbitrary-dev** [comment]
Added following to my `.vimrc` as a workaround:

```
set cursorline
hi CursorLine cterm=none
map <silent> <leader>cl :call ToggleCursorLine()<CR>
function ToggleCursorLine()
  if match(execute('hi CursorLine'), 'ctermbg') >= 0
    hi CursorLine ctermbg=none
  else
    hi CursorLine ctermbg=52
  endif
endfunction
```
