### ISSUE TITLE
system clipboard bug

### ISSUE THREAD

**Issue by Laumm** [neoclide/coc-lists#79]
### QUESTION
When I copy a string  from the system clipboard, I only get the first character. If I use the vim system register, I can get all the contents.

### ENVIRONMENT
- Macos 10.14.6
- Vim 8.1.1722

###  Examples

![image](https://user-images.githubusercontent.com/42160960/79547970-4ef8d900-80c7-11ea-955b-c072d481c1fc.png)
Copy the "hello world" using the vim system register

![image](https://user-images.githubusercontent.com/42160960/79548050-69cb4d80-80c7-11ea-8541-107e89c6bdbc.png)
Copy the "hello world" using the system clipboard[C-v]

**Comment by chemzqm** [comment]
Can't fix, system clipboard not work well with vim's `getchar` function, you have to use vim's system register.
