### ISSUE TITLE
list.insertMappings : get current word wrong

### ISSUE THREAD

**Issue by Laumm** [neoclide/coc-lists#81]
### QUESTION
When I set up a custom mapping to getting the cursor word
` "<C-r>": "eval:expand('<cword>')"`
I get a unexpected string `Press`

### CONFIG
![image](https://user-images.githubusercontent.com/42160960/79720050-65df3b80-8312-11ea-991b-b0bda528c5a4.png)
### RESULT
![image](https://user-images.githubusercontent.com/42160960/79720257-c8383c00-8312-11ea-8e63-54a456bc014f.png)

**Comment by chemzqm** [comment]
It's expected since your cursor doesn't leave list window, you have to command line argument `--input`
