### ISSUE TITLE
Can't include generated css files

### ISSUE THREAD

**Issue by eduardoarandah** [neoclide/coc-lists#83]
### For example, bootstrap utilities (this is the goal):

![image](https://user-images.githubusercontent.com/4065733/80823659-a6587800-8ba2-11ea-99e0-ae901907153a.png)

# I tried with source.files

CocConfig:

```
"list.source.files.command": "ls public/css",
"list.source.mru.ignoreGitIgnore": true
```

But doesn't work: 

![image](https://user-images.githubusercontent.com/4065733/80823879-03542e00-8ba3-11ea-8f84-49372f4d5288.png)

## I tried using ripgrep

CocConfig:

```
  "list.source.files.command": "rg",
  "list.source.files.args": [ '--files', '--no-ignore-vcs' ],
  "list.source.mru.ignoreGitIgnore": true

```

![image](https://user-images.githubusercontent.com/4065733/80823367-216d5e80-8ba2-11ea-80bd-42b8c9a0b67e.png)

## I double checked using ripgrep in comand line

Command works! but completion doesn't

`rg --files --no-ignore-vcs `

![image](https://user-images.githubusercontent.com/4065733/80823468-524d9380-8ba2-11ea-8007-a74d6b9db9dc.png)

## Is this the best way to do it?

- How to include those css classes?

## Should I use tags?

I tried using ctags 

```
ctags -R --fields=+aimlS --languages=css --exclude=node_modules
```

And file looks fine, but still doesn't work:
![image](https://user-images.githubusercontent.com/4065733/80824414-0a2f7080-8ba4-11ea-92bb-0e299f1ec637.png)

**Comment by chemzqm** [comment]
coc-lists has nothing to do with completion
