### ISSUE TITLE
Navigate result list without the arrows

### ISSUE THREAD

**Issue by agtonybarletta** [neoclide/coc-lists#84]
I am new to this extension so I'm probably missing something.

When I type the command 
```
:CocList grep
```
and then I insert some string, it finds the list of files but I can't navigate the list easily.
With enter it opens the first file.
With the option --number-select it opens a file with the number keys only if the file number is less than 9.
I can move through the list using the arrows, but that doesn't seem natural to vim/neovim users.
Is there a way to move through the list of results without using the arrow keys? 
I am thinking about a mapping that let me get out of the fuzzy search and move in the list with vim movement (ijkl), or a map that let me scroll the list  page (like ctrl+d) and then use the number to select the file. Even better a command/option/mapping that let me open that list in a split and then select the file to open from that. 
Is there something already implemented to do that ? 
Am I missing something ?

**Comment by chemzqm** [comment]
Use `<C-j>` and `<C-k>` on insert mode.
