### ISSUE TITLE
CocList mru 如何显示最近使用的所有文件呢

### ISSUE THREAD

**Issue by loyalpartner** [neoclide/coc-lists#86]
默认情况下只显示当前目录下最近使用的文件，
我想显示所有最近使用的文件

**Comment by pacmanzou** [comment]
> 默认情况下只显示当前目录下最近使用的文件，
> 我想显示所有最近使用的文件

CocList mru -A

**Comment by pacmanzou** [comment]
@loyalpartner

**Comment by loyalpartner** [comment]
> @loyalpartner

tks
