### ISSUE TITLE
Several seconds to exit CocList?

### ISSUE THREAD

**Issue by tmpm697** [neoclide/coc-lists#88]
Produce:
```
1. open vim
2. type in command mode: CocList
3. press esc/ctrl-[ to exit
4. observe few seconds for the buffer to disappear
```
system: archlinux up-to-date / vim 8.2 1-814 / coc-lists up-to-date

 I expect the buffer/terminal window disappear instantly, but it took few seconds (3-4s) to disaapear? Can we avoid this?

**Comment by tmpm697** [comment]
set updatetime to 300ms seems doesn't help much. still slow to disappear.

**Comment by chemzqm** [comment]
Try minimal vimrc

**Comment by tmpm697** [comment]
I tried without vimrc and with empty vimrc (touch ~/.vimrc)

without vimrc has significant boost speed compare to an empty vimrc, why is that happens?

with vimrc with my setup, same slow speed with empty vimrc

**Comment by tmpm697** [comment]
After use ctrl-c insteand of ctrl-[ issue it closed instant now.: https://github.com/neoclide/coc.nvim/issues/639
