### ISSUE TITLE
Blink "FUZZY" when open CocList in vim?

### ISSUE THREAD

**Issue by tmpm697** [neoclide/coc-lists#89]
This doen't happen with nvim.

Tested with minimal vimrc
Produce:
```
open vim
:CocList
observer blink at "FUZZY" line like it drawn several time cause it flick
```

The same issue happen when I open :terminal in vim, not happen with nvim.

So this issue my comes from bultin terminal in vim, how to prevent it or is it a bug from vim?

**Comment by chemzqm** [comment]
You can disable cursor change of list

**Comment by tmpm697** [comment]
@chemzqm how can I `disable cursor change of list` in vim? Thanks.

**Comment by chemzqm** [comment]
`:h g:coc_disable_transparent_cursor`

**Comment by tmpm697** [comment]
I have `let g:coc_disable_transparent_cursor=1` in `vimrc` but issue still happens. I don't have this issue in neovim with or without `coc_disable_transparent_cursor` set to 1.

**Comment by chemzqm** [comment]
If transparent cursor not work for you, we can't help.
