### ISSUE TITLE
Add grep --hidden option

### ISSUE THREAD

**Issue by flipxfx** [neoclide/coc-lists#9]
Add --hidden option for rg grep to search files that are hidden

**Comment by chemzqm** [comment]
You can use `"list.source.files.args"` in settings.json to add it.

**Comment by flipxfx** [comment]
Sorry I meant for grep. Updated accordingly.

**Comment by chemzqm** [comment]
Use `"list.source.grep.command"` and `"list.source.grep.args"`

**Comment by flipxfx** [comment]
Ok that worked. Didn't realize I could pass other options than the ones listed. I was confused by the way you can only pass args to files if you specify the command but it looks like it's not required for grep.

**Comment by chemzqm** [comment]
> by the way you can only pass args to files if you specify the command

What does `you can only pass args to files if you specify the command` means?

**Comment by flipxfx** [comment]
So if I specify `'files.args': ['--color', 'never', '--files', '--hidden']`, but I don't have `'files.command': 'rg'`, then the `'files.args'` are ignored.

But for grep I don't have to specify `'grep.command': 'rg'` for it to grab the `'grep.args'` and append them.

**Comment by chemzqm** [comment]
It is confuing, I've fixed it.
