### ISSUE TITLE
grep results highlight unexpected.

### ISSUE THREAD

**Issue by Cosss7** [neoclide/coc-lists#95]
![Screenshot_20200722_180947](https://user-images.githubusercontent.com/12772673/88165607-89cf5780-cc48-11ea-9bee-5686792e43d2.png)
Because some special key surround it.

(For showing the line content in the picture, I have to write code like this.emit('error', line) in grep.ts. How do I print log in coc extension ?)

**Comment by chemzqm** [comment]
Use `logger` from context and get log filepath by `:CocOpenLog`.

**Comment by Cosss7** [comment]
Hi~, thx for your replay. @chemzqm 
> Use `logger` from context and get log filepath by `:CocOpenLog`.

I want to print content of `line` in Task#start() in grep.ts. But I can't get context there.

And I edit my issue's description in detail.

**Comment by chemzqm** [comment]
It's expected, you have to change your terminal color `:h terminal-configuration` or change args of grep source, checkout `:h rg`

**Comment by Cosss7** [comment]
Thx, I misunderstand it.
